export const skillsData = [
  "Cloud Computing",
  "Cyber Security",
  "Incident Response",
  "Relational Databases",
  "Software as a Service (SaaS)",
  "AWS",
  "Python",
  "Java",
  "Git",
  "BitBucket",
  "GitLab",
  "Rest",
  "Docker",
  "Jira",
] as const;
